name: Testing Deployment

on:
  workflow_call:
    secrets:
      CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true

jobs:
  jira_deploy_prod:
      runs-on: ubuntu-latest

      needs: stencil_deploy_prod

      if: github.event_name == 'push'

      steps:
      - name: Deploy to Test Jira
        run: |
          echo "github.event_name: ${{github.event_name}}"
          echo "github.ref: ${{github.ref}}"
          echo "DEPLOY_STATE=successful" >> $GITHUB_ENV
          echo "Deploying to Test..."

      - name: Failed Jira Deployment
        if: failure()
        run: echo "DEPLOY_STATE=failed" >> $GITHUB_ENV

      - name: Parse Jira Keys from All Commits
        id: jira_keys
        if: always()
        uses: HighwayThree/jira-extract-issue-keys@master
        with:
          is-pull-request: false
          parse-all-commits: ${{ github.event_name == 'push' }}
          commit-message: ${{inputs.jira-keys}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirm Deploy State and Jira Key Values
        if: always()
        run: |
          echo "DEPLOY_STATE: ${{env.DEPLOY_STATE}}"
          echo "Jira Keys: ${{steps.jira_keys.outputs.jira-keys}}"

      - name: Push Deployment Info to Jira
        if: steps.jira_keys.outputs.jira-keys != ''
        id: push_deployment_info_to_jira
        uses: HighwayThree/jira-upload-deployment-info@master
        with:
          cloud-instance-base-url: 'https://minnek.atlassian.net'
          client-id: '${{ secrets.CLIENT_ID }}'
          client-secret: '${{ secrets.CLIENT_SECRET }}'
          deployment-sequence-number: '${{ github.run_id }}'
          update-sequence-number: '${{ github.run_id }}'
          issue-keys: "${{ steps.jira_keys.outputs.jira-keys }}"
          display-name: "Deployment to Test"
          url: "${{github.event.repository.url}}/actions/runs/${{github.run_id}}"
          description: "Action for Deployment to Test"
          last-updated: '${{github.event.head_commit.timestamp}}'
          label: 'Test Deployment'
          state: '${{env.DEPLOY_STATE}}'
          pipeline-id: '${{ github.repository }} ${{ github.workflow }}'
          pipeline-display-name: 'Workflow: ${{ github.workflow }} (#${{ github.run_number }})'
          pipeline-url: '${{github.event.repository.url}}/actions/runs/${{github.run_id}}'
          environment-id: 'test'
          environment-display-name: 'Test'
          environment-type: 'testing'
